--- 
log_file: /home/myblogadmin/myblog/current/log/myblog.log
port: 54300
cwd: /home/myblogadmin/myblog/current
environment: production
pid_file: /home/myblogadmin/myblog/current/tmp/pids/mongrel.pid
servers: 1